service: sitemonitoring

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 512
  environment:
    TABLE_NAME: ${self:custom.tableName}
    WATCH_URLS: ${env:WATCH_URLS}
  apiKeys:
    - ${opt:stage}-SiteMonitoring

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-Incident
  tableThroughputs:
    prod: 1
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

functions:
  createLocalDb:
    handler: handlers.createLocalDb
    events:
      - http:
          path: create-local-db
          method: get
  getAppVersion:
    handler: handlers.getAppVersion
    events:
      - http:
          path: version
          method: get
          private: true
  schedule:
    handler: handlers.schedule
    events:
      - http:
          path: schedule
          method: get
  inspect:
    handler: handlers.inspect
    timeout: 30
    events:
      - http:
          path: inspect
          method: get

  incidents:
    handler: handlers.getIncidents
    events:
      - http:
          path: incidents
          method: get

resources:
  - ${file(resources/dynamodb-table.yml)}
